---
- name: Copy a config file in place
  copy:
    src: awslogs.conf
    dest: /tmp/awslogs.conf
    group: root
    mode: 0600
    owner: root

- name: Download the installer
  get_url:
    dest: /tmp/awslogs-agent-setup.py
    group: root
    owner: root
    mode: 0600
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py

- name: Check if aws log is already running
  shell: ps aux | grep '[a]ws logs push'
  register: aws_logs_process
  changed_when: False

- name: Install the CloudWatch Logs agent
  shell: python /tmp/awslogs-agent-setup.py -n -r {{ aws_region }} -c /tmp/awslogs.conf
  when: aws_logs_process.rc > 0

- name: Copy systemd unit file
  copy:
    src: awslogs.service
    dest: /lib/systemd/system/awslogs.service
    owner: root
    group: root
    mode: 644
  register: systemd_file

- name: Refresh systemctl service
  shell: "systemctl daemon-reload"
  when : systemd_file.changed

- name: Enable & start awslogs service
  service:
    name: awslogs
    enabled: yes
    state: started
