---

# Pre-requisities install monitoring script

- name: Ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - perl-Switch
    - perl-DateTime
    - perl-Sys-Syslog
    - perl-LWP-Protocol-https
    - perl-Digest-SHA.x86_64