---
- name: Put a config file in place
  template:
    dest: /tmp/awslogs.conf
    group: root
    mode: 0600
    owner: root
    src: awslogs.conf.j2

- name: Download the installer
  get_url:
    dest: /tmp/awslogs-agent-setup.py
    group: root
    owner: root
    mode: 0600
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py

- name: Install the CloudWatch Logs agent
  shell: python /tmp/awslogs-agent-setup.py -n -r {{ aws_regions }} -c /tmp/awslogs.conf

- name: Enable awslogs service
  service: name=awslogs enabled=yes

- name: Start awslogs service
  service: name=awslogs state=started
