---

# Pre-requisities install monitoring script & cloudwatch logs

- name: Ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - perl-Switch
    - perl-DateTime
    - perl-Sys-Syslog
    - perl-LWP-Protocol-https
    - perl-Digest-SHA.x86_64

# Install AWS logwatch agent

- name: Ensure a list of packages installed
  yum:
    name:
      - awslogs
    state: latest
  register: awslogs_package_installation

- name: Start service awslogs
  service:
    name: awslogs
    enabled: yes
    state: "{{ awslogs_service_state }}"
  when: package_installation.changed